tasks:
  shtzz:
    rss: https://cgrsshub.herokuapp.com/dsndsht23/gqzwzm
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: c31df97cae212ee0b9da
      path: /home/download/
  javdbwm:
    rss: https://cgrsshub.herokuapp.com/javdb/home/uncensored/2/2
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: c31df97cae212ee0b9da
      path: /home/download/
  javdbym:
    rss: https://cgrsshub.herokuapp.com/javdb/home/censored/2/2
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: c31df97cae212ee0b9da
      path: /home/download/
  javdbom:
    rss: https://cgrsshub.herokuapp.com/javdb/home/western/2/2
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: c31df97cae212ee0b9da
      path: /home/download/
  2048cn:
    rss: https://cgrsshub.herokuapp.com/2048/bbs/16
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: c31df97cae212ee0b9da
      path: /home/download/