tasks:
  141jav:
    rss: https://cgrsshub.herokuapp.com/141jav/tag/amateur
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: 820184b93cb90209b265
      path: /home/download/
  141ppv:
    rss: https://cgrsshub.herokuapp.com/141ppv/new
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: 820184b93cb90209b265
      path: /home/download/
  onejav:
    rss: https://rsshub.app/onejav/tag/amateur
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: 820184b93cb90209b265
      path: /home/download/
  shtwmfc2:
    rss: https://cgrsshub.herokuapp.com/dsndsht23/36/368
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: 820184b93cb90209b265
      path: /home/download/
  javdb_ranking:
    rss: https://cgrsshub.herokuapp.com/javdb/rankings/uncensored
    accept_all: yes
    aria2:
      server: 127.0.0.1
      port: 6800
      secret: 820184b93cb90209b265
      path: /home/download/